services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle_reservas
    ports:
      - "1521:1521"
    environment:
      - ORACLE_DATABASE=reservas_db
      - ORACLE_PASSWORD=oracle
      - APP_USER=reservas
      - APP_USER_PASSWORD=reservas
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: